### PR TITLE
Fix sidebar samples size

### PR DESCRIPTION
**Pull request by GioviQ**

### CODE REVIEW

**Comment by Joelius300** [comment]
Thank you! I was wondering how to fix that. Btw, this would fix #80.

I'd love to merge but unfortunately I'm already working on a grand rework of the samples (see the [dedicated issue](https://github.com/mariusmuntean/ChartJs.Blazor/issues/122) and [branch](https://github.com/mariusmuntean/ChartJs.Blazor/tree/samples-reorg)) and will therefore close your PR. The rework aims to make the samples similar to the ones of Chart.js which will also greatly improve the layout including mobile support.

If you're still motivated to contribute (which I hope of course), we will very much appreciate contributions to the samples once the samples-reorg branch is merged :)

**Comment by GioviQ** [comment]
Ok

I need to include https://github.com/haiiaaa/chartjs-gauge but if you are not interested, I will create my own repository.

**Comment by Joelius300** [comment]
Of course we're interested, we love contributions! The issue is that @mariusmuntean (the owner of the repository) doesn't seem to be active anymore and I only have very little free time to work on the library. All of my available resources currently go into the samples..

My suggestion for you is to fork the repository and start with the addition of the plugin. You can use your version of the library instead of ours for as long as you'd like (the library is MIT licensed). If you would like to contribute your addition back to us, you can open a (I suggest drafted since it's going to take a while) pull request, which we can review and integrate in our repository when we have the time to do so.  
I cannot promise anything since the library and its maintainers aren't in the base position currently but I encourage you to contribute ❤️ 

Ps. I created #153 to provide some insight and clarity about what's currently going on with the samples.

**Comment by GioviQ** [comment]
@Joelius300 you have the rights on this repository, isn't it? Anyway without the owner this repository is dead.

**Comment by Joelius300** [comment]
I have write access and have been doing a lot of work for this repository in the past (mostly issues but also new features and bug fixes). However I'm limited since I can't publish preview releases without pushing to the releases branch, I can't update the demo page and in general _I'm not the owner_. While I consider myself the primary maintainer, it's still not the same as the owner.

**Comment by GioviQ** [comment]
if @mariusmuntean  is unreachable and you are the only contributor, you should consider to continue with your fork.

With right access you can update the readme and describe the situation.

I am contributor of https://github.com/enkodellc/blazorboilerplate which implements runtime blazor host model switch.

**Comment by GioviQ** [comment]
A better repository name should be Blazor.Chart.Js

**Comment by GioviQ** [comment]
I can host samples here https://blazor-server.quarella.net/ or something like blazor-chartjs.quarella.net if you think to be the new project leader.

**Comment by Joelius300** [comment]
Thank you for the offer but I won't do anything like this currently.

Here some insights from me - I wanted to let this out somewhere anyway. I'll probably link to it later.

The way I got into this project is weird.. I used it once in a small application of mine, that has been completely rebuilt without blazor now. I'm currently not using blazor anywhere and I don't plan to come back to it until it has matured a bit (probably .NET 5 or 6). That being said, this project was an amazing opportunity for the unexperienced me to learn about Blazor, Chart.js, JSON, Open Source, git and GitHub. Since then I made a lot of progress and you can also see that in this library. However, I also took a big part in really bad features like the covariant datasets and since I know that an official dotnet repository is using our library in their sample project, I don't want to let things like that slide.  
My goal is to finish 2.0 which should bring a version that _should've been 1.0_. Then it's searching new maintainers and moving on. This project could have a bright future but with the owner being inactive and the only active contributor constantly losing time and motivation, it's doomed to fail if noone comes to save it..

**Pull request closed without merging**
