### PR TITLE
Layout Configuration #156

### PR DESCRIPTION
**Pull request by ipax77**
Please let me know if this is the correct way to implement new features. I'd like to do more pull requests, ChartJS is cool ;)

### CODE REVIEW

**Comment by Joelius300** [comment]
Thanks for the Pull Request.

I see you've pushed a new commit to fix #170. When working with PRs, you should do you work in pieces, like you probably do in your own development environment too. One PR per feature/fix/whatever (usually that lines up pretty well with one PR per issue).  
Since this fix has nothing to do with the layout configuration, you should create a new branch and submit a new PR with just the fix for #170. That way it's easier to review and merge.

The fix is simple and I think we can merge it in fast but could you make sure to indent the if correctly and leave one empty line before the nested if (so between `config.options.scale.ticks.callback = .....` and `if (!config.opti...`) please?

The layout configuration I'd have to take a look at when I have more time but there are some issues like the lowercase property names and the explicit default value.

To get a clean history on this PR, you should reset your branch and create a single commit for adding the layout configuration. Then rebase to the current master and force push (that's fine since it's on a separate branch of your fork). After that it should be ready for review. If you're interested, you can do that all in one single interactive rebase :)

**Comment by ipax77** [comment]
Ok, ty for clarification! I think I got it

**Comment by Joelius300** [comment]
Thanks for #171 👍🏼 

If you want you can submit a new PR for the layout configuration and I'll take a look at it when I get time. Also you closed this PR so you don't really need the rebase stuff. I said that in case you wanted to continue using this PR for the layout configuration but now you've reset it to master so the changes are gone. [In case you need to recover them](https://stackoverflow.com/questions/2510276/how-to-undo-git-reset).. :)

**Comment by ipax77** [comment]
Thx again for ur patience, I am new to this pull request thing ..
Now, my workflow is keep the forks master in sync with this master and submit pull requests from fork branches. And I have a branch in the fork (pax) with all my branches merged. 
What I am missing then is the check if there are merge conflicts to the master, but for theses simple tasks it should be fine I guess

**Pull request closed without merging**
