### PR TITLE
Update samples based on mashbrno PR

### PR DESCRIPTION
**Pull request by larshg**
Hey @mariusmuntean 

I tried to update the samples based on @mashbrno changes.

I had to lower the targetframework to be netstandard2.0, else I couldn't get the samples working.

There is however a glitch that I haven't figured out yet, I can only see a chart once - if I re-navigate to page, it doesn't redraw the chart.

Maybe you can try out the changes?

### CODE REVIEW

**Comment by mariusmuntean** [comment]
@larshg @mashbrno many thanks for your contributions!
I will have a look a them today.

It is very important to me that the samples work.

**Comment by mariusmuntean** [comment]
The code looks good to me.
I had some issues with my Windows dev machine that prevented me from running everything locally.

If I get the code to run Saturday morning I'll merge the PR and you can expect a release the same day.

**Comment by larshg** [comment]
Nice to hear from you @mariusmuntean.

But I'll add another request soon, in which I have made some more changes and reorganization.

**Comment by mariusmuntean** [comment]
@larshg found time to get the PR code running (client-side) and everything looks fine.
Do you think I should hold off a bit with merging this PR and just have a look at the next one when it comes?

**Comment by larshg** [comment]
Yeah, I just uploaded the changes - take a look :)

**Pull request merged**
