### PR TITLE
Update to .net 3.0 core preview4.

### PR DESCRIPTION
**Pull request by larshg**
Tried to follow the guidance [here](https://devblogs.microsoft.com/aspnet/asp-net-core-updates-in-net-core-3-0-preview-4/)

### CODE REVIEW

**Comment by realbronto** [comment]
thank you, worked for me!

**Comment by johndevs** [comment]
Any chance of a new version?

**Comment by mariusmuntean** [comment]
Yes, for sure!
I moved and there are still unopened moving boxes. One of them is my PC.
If everything goes well, during the next week or so I will pick up where I left this project.

**Comment by larshg** [comment]
Closing in favor of #31

**Pull request closed without merging**
